#for database credentials and jwt secret
apiVersion: v1
kind: Secret
metadata:
  name: exam-db-secret
type: Opaque
stringData:
  DB_USER: postgres
  DB_PASS: "1234"
  DB_NAME: examdashboard
  JWT_SECRET: examdashboard-dev-secret-key-that-is-at-least-256-bits-long-for-hs256
