server:
  port: 8080

spring:
  application:
    name: exam-dashboard
  
  datasource:
    url: jdbc:postgresql://localhost:5432/examdashboard
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

app:
  jwt:
    secret: examdashboard-dev-secret-key-that-is-at-least-256-bits-long-for-hs256
    expiration-ms: 86400000

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
